# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" "rtsx_usb_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/193248f3-fc8c-4f1b-ab0a-4037949c81ba";
    fsType = "btrfs";
    options = ["subvol=@" "noatime" "compress=zstd:1"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/193248f3-fc8c-4f1b-ab0a-4037949c81ba";
    fsType = "btrfs";
    options = ["subvol=@home" "noatime" "compress=zstd:1"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/193248f3-fc8c-4f1b-ab0a-4037949c81ba";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime" "compress=zstd:1"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DA95-76B6";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/29e4a280-61ec-4e08-8cfc-dfb90d1fd29f";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
