# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "ums_realtek" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c7dd11d8-281d-41d1-8205-b46fe79e7b6b";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress=zstd:1" "autodefrag"];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c7dd11d8-281d-41d1-8205-b46fe79e7b6b";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd:1" "autodefrag" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c7dd11d8-281d-41d1-8205-b46fe79e7b6b";
      fsType = "btrfs";
      options = [ "subvol=@nix"  "noatime" "compress=zstd:1" "autodefrag" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9d4deed5-9f7d-4621-b09c-3867419252cf"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
