# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "ehci_pci" "xhci_pci_renesas" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  # T14 Gen1 AMD (Renoir/Zen2): amd_pstate=active is passed so the kernel uses it
  # if firmware CPPC support is present; otherwise acpi_cpufreq takes over.
  # The CPU frequency governor is owned by power-profiles-daemon (utils.nix);
  # GameMode requests the performance profile from PPD automatically during gaming,
  # which saves battery when idle without sacrificing peak throughput.
  boot.kernelModules = ["kvm-amd" "thinkpad_acpi" "amd-pstate"];
  boot.kernelParams = ["amd_pstate=active" "acpi_backlight=native" "psmouse.synaptics_intertouch=0"];

  boot.kernelPackages = pkgs.linuxPackages_zen;
  hardware.trackpoint.enable = lib.mkDefault true;
  hardware.trackpoint.emulateWheel = lib.mkDefault config.hardware.trackpoint.enable;

  services.fwupd.enable = true;

  networking.networkmanager.enable = false;
  networking.wireless.iwd.enable = true;

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.bluetooth.enable = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
